dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
env:
  secure: RymZPAUgaq7nxQsu4Cj0GmEyQ/KlLfvB8hoMzK94l+t+0yrUPe1bA/nGGCYD1KOJeG8mHbSg3QdQ+RC+xaV5TOGDSP2CNCUewgwrqVcWKsXzZFmqk1qEvwI5m30oY8C/0VQEg9KnxvDU7STvGFBh4hCRMWWigib/GI0rnK3vbGognd+4AZGKCpzVwluGADnt9g125iWoljGoD26Gf9EaiGpGe1shUEPDnMe1vw69nD7TB/2lcFdyDH7wzeswKPmlv9LGxG9AFh11IuNkAtmtRUqSqrh72e1JHe+zB4/DQc34wiZcOp81J8bwFbtLGY63cfG6qBgt3im1dEpCnz7ZOyiNE+DkNI8QqsCfC/ic1yP0ka718oMcM4dpc/KgW9Nt88n98lCwwQMBdWhPtZdf2QnDtIb+S2SSS4WIRjjTA1VHWqlD7wzaLQvScJQV0wNoTlbkfFstzh1RF5BS7a/OMTIPZKGNOnYdtsDm2DgQmRBaYmJjYLsHaHYxpPWjX71VT7g7FsLH0x9DGkTjEKm8VyXR1HqU1XNka0wdqEkSPCHgkXBqHRKYlUiE+nwexyHeubopRhdButdIkjV9RHPiiRK7mIjLqXT6+KoCVRSk5Y410yZDe9xmus3cIkPgfh5PxsqkXTXjXilXXP75CQlk8JwFi3BRzAAU0thjgcz8tGYO8=
jobs:
  include:
  - stage: tests
    script:
    - npm run start-ganache &
    - npm run test
  - stage: Deploy and publish
    if: "(NOT type IN (pull_request)) AND (branch = develop)"
    script:
    - "./scripts/pullContracts.sh"
    - "./scripts/migrate.sh rinkeby"
    - "./scripts/migrate.sh kovan"
    deploy:
      provider: npm
      skip_cleanup: true
      email: razvan@centrifuge.io
      api_key:
        secure: hVd/MuZPhvzseACZ6VEpOos6+rTY4jZBTIUorbi62+RXpQTSFtZcGjA6dCCfsuHJ5JR6BAIL5WncSEJTftrkVor350U6yt5gqde6TJ6j9IPKhabU3e5o3kQz05iKQVGGHyzZzVCvKZQV0bqKI0OFTQA7pqwu0G6Qf3nA3aZTgdMAsF0klJdpQykqWfgnwYQJthlVYayNJ5Vp1fPfLw0Lq98bN7KNS67+YhF5xRF5AgZpd95JM/6cuRLo0hokUYL7DMvgKTEsWECLgFVqH0fYS/QQNQfQwdPwrT3RQYNCyaFco+Ueq1Zy7li9+57ZnN9PLZpyL7lFTUBfILcBua0jYSX2t35cn/J8BdwukXgZt0HjhEQQIE0mdeJSKdHOWDR4fuAC8biHO+ZsOHBhfEAhl44qDE9qMPgJX2SANkppiTxAzmbIn3r++vYg6S+wcUaaFpJlCjPAx0/ioPyp63WocSvoJkJY7OzfOJyXPD1xR1HeDH4isvD8zz+QzTKGMtiaJNlko1yUnGlyMh9r1TMDJXnsV8J7R+1RIrXjkA1XuO6gCuppRpGKyDe6gBGxjRNIOdHc9pYGY2NrbEngjI93r2snBjj3HzWWtWEmZSdnzYAdq9Uf2AO+OOLh/rzTg5Yz1iAWTmGb9XFNYuBZsnEyB9IBH0+dUf6rEQROueYRsXQ=
      on:
        repo: centrifuge/centrifuge-ethereum-contracts
        branch: develop
